"""Write the deck's intro action keys for the Crooked Moon: one Foundry macro per entrance, placed on the board of every
scene that NPC appears on. Output: audio-catalogue/campaigns/crooked-moon-intro-keys.json (the plan) and
crooked-moon-intro-keys.apply.js (a GM console script, TEST WORLD ONLY, data embedded — nothing is written into Data)."""
import json
import re
from pathlib import Path

HERE = Path(__file__).parent
MC = HERE.parents[1]  # tools/entrances → the repo
CAT = MC.parent / "audio-catalogue" / "campaigns"  # the sibling catalogue folder (not a git repo)
src = (MC / "scripts/cm-entrances.js").read_text(encoding="utf-8")
entries = json.loads(re.search(r"export const CM_ENTRANCES = (\[.*\]);", src, re.S).group(1))

# Where each NPC shows up: the adventure's map numbers (a scene named "12.1 …" and its Colored copy).
SCENES = {
    "vagrant": ["10.1"], "druskenvald": ["10.3"], "trainhopper": ["10.8", "10.1"], "mayor": ["11.1", "11.2"],
    "vessla": ["12.4"], "crooked": ["12.1", "12.2", "12.3"], "boogle": ["12.2", "12.1", "12.3", "12.4"], "wisp": ["12.3", "12.1"], "lurker": ["12.2"], "monweasel": ["12.2", "12.3"], "toys": ["12.3"], "jericho": ["13.3"], "harvest": ["13.3"],
    "abbottf": ["14.3"], "jaeger": ["14.1"], "olaf": ["14.1"], "cromwell": ["14.1"], "sinner": ["15.2"],
    "stonoga": ["16.5"], "widow": ["17.3"], "hugo": ["17.1", "17.2"], "worm": ["17.3"], "blight": ["18.4"],
    "reapertf": ["19.7"], "golubtf": ["11.2", "20.2"], "fools": ["21.1"], "foolstf": ["21.2"], "crowdemon": ["13.2", "13.3"], "adelaide": ["13.1", "13.3"],
    "belkin": ["17.1"], "belkintf": ["17.2"], "coven": ["22.5"], "wicker": ["23.3"],
    "horned": ["24.3"], "queen": ["24.3"],
    "theodora0": ["11.2"], "law": ["11.2"], "rain": ["11.2"], "weston": ["11.2"], "rusty": ["11.1", "11.2"], "mori": ["11.2"],
    "jenkins": ["11.2"], "farmers": ["11.2"], "renathyrolaf": ["14.1"], "jaeger0": ["14.1"], "cromwell0": ["14.1"],
    "crossroads0": ["15.2"], "bayou": [], "lethica0": ["17.1"], "yorgrimisolde": ["19.1"], "finale": ["24.3"],
}
# The generic intros carry their own scenes (generic.json, from the book pass).
for g in json.loads((HERE / "generic.json").read_text(encoding="utf-8")):
    SCENES[g["key"]] = g["scenes"]
assert set(SCENES) == {e["key"] for e in entries}, set(SCENES) ^ {e["key"] for e in entries}

def first_src(html):
    m = re.search(r'src="([^"]+)"', html or "")
    return m.group(1) if m else None


# `img` is the key's face — for a transformation, the form the party knows, so the DM sees whom he presses it for.
# `show` is what a plain table (no mobile-command) is shown: the NPC — for a transformation, the monster it becomes.
# Keys whose banner picture is a CROP hiding a secret: the whole file would give it away (Raum behind Jericho, Belkin's
# open skull), so a plain table gets the entrance in chat — name and line — instead of a picture.
NO_PLAIN_PICTURE = {"jericho", "belkin"}
plan = [{"key": e["key"], "label": e["short"], "name": e["name"], "sub": e["sub"], "img": e["portrait"],
         "show": "" if e["key"] in NO_PLAIN_PICTURE else first_src(e.get("art2")) or e["portrait"], "scenes": SCENES[e["key"]],
         "match": e.get("match") or [], "appears": bool(e.get("appears"))}
        for e in entries]
(CAT / "crooked-moon-intro-keys.json").write_text(json.dumps(plan, indent=1, ensure_ascii=False), encoding="utf-8")

JS = r"""// Deck Command — the Crooked Moon's INTRO action keys. TEST WORLD ONLY. Paste into the GM's console.
// One macro per NPC entrance (mobile-command §40.6 "Intros"; deck-command ledger 150 action keys), in the Macros
// folder "Deck Command · Intros", each placed in the first empty box of the board of every scene that NPC appears on
// (a scene named "12.1 …" and its Colored copy). Creates or updates, never deletes; a key already on a board stays
// where he moved it. Generated by gen_intro_keys.py from mobile-command's scripts/cm-entrances.js.
(async () => {
  if (game.world?.id !== "offline-test") return { refused: `world is ${game.world?.id}, not offline-test` };
  if (!game.user?.isGM) return { refused: "not a GM" };
  const ID = "deck-command";
  const PLAN = __PLAN__;

  const folderName = "Deck Command · Intros";
  const folder = game.folders.find((f) => f.type === "Macro" && f.name === folderName)
    ?? await Folder.implementation.create({ name: folderName, type: "Macro" });

  const commandFor = (p) => [
    `// Deck Command action key: ${p.name}'s entrance. With mobile-command, its themed banner (Intros);`,
    `// on a plain table, the NPC's picture to everyone. Made by crooked-moon-intro-keys.apply.js.`,
    `const o = ${JSON.stringify({ key: p.key, name: p.name, sub: p.sub, img: p.show, match: p.match, appears: p.appears })};`,
    `const act = game.modules.get("deck-command")?.api?.act;`,
    `return act ? act.intro(o) : globalThis.MobileCommand?.playEntrance?.(o.key);`,
  ].join("\n");

  const report = { created: [], updated: [], placed: [], alreadyThere: [], noScene: [] };
  const macros = {};
  for (const p of PLAN) {
    const data = { name: p.label, type: "script", img: p.img, command: commandFor(p), folder: folder.id, flags: { [ID]: { intro: p.key } } };
    let m = game.macros.find((x) => x.flags?.[ID]?.intro === p.key);
    if (m) { await m.update(data); report.updated.push(p.label); }
    else { m = await Macro.implementation.create(data); report.created.push(p.label); }
    macros[p.key] = m;
  }

  const SLOTS = 10;
  const pagesOf = (scene) => {
    const raw = scene.flags?.[ID]?.sounds;
    const list = Array.isArray(raw) ? raw : raw && typeof raw === "object" ? Object.values(raw) : [];
    return list.map((pg) => Array.from({ length: SLOTS }, (_, i) => {
      const v = (Array.isArray(pg) ? pg : Object.values(pg ?? {}))[i];
      return typeof v === "string" && v ? v : null;
    }));
  };
  // A map number names every part of that map: "14.1" covers "14.1.1 …" and "14.1.2 …" (and their Colored copies).
  const numOf = (name) => /^(\d{1,2}(?:\.\d{1,2})+)\s/.exec(name)?.[1] ?? null;
  const covers = (planNum, sceneNum) => sceneNum === planNum || sceneNum.startsWith(`${planNum}.`);
  for (const scene of game.scenes.contents) {
    const num = numOf(scene.name);
    if (!num) continue;
    const wanted = PLAN.filter((p) => p.scenes.some((n) => covers(n, num)));
    if (!wanted.length) continue;
    const pages = pagesOf(scene);
    let changed = false;
    for (const p of wanted) {
      const uuid = macros[p.key].uuid;
      if (pages.some((pg) => pg.includes(uuid))) { report.alreadyThere.push(`${scene.name}: ${p.label}`); continue; }
      // Page 1 first — the key he reaches without paging — then any later gap, then a fresh page.
      let at = null;
      for (let pg = 0; pg < pages.length && !at; pg++) {
        const i = pages[pg].indexOf(null);
        if (i >= 0) at = [pg, i];
      }
      if (!at) { pages.push(Array(SLOTS).fill(null)); at = [pages.length - 1, 0]; }
      pages[at[0]][at[1]] = uuid;
      changed = true;
      report.placed.push(`${scene.name}: ${p.label} → page ${at[0] + 1}, box ${at[1] + 1}`);
    }
    if (changed) await scene.setFlag(ID, "sounds", pages);
  }
  const seen = game.scenes.contents.map((s) => numOf(s.name)).filter(Boolean);
  for (const p of PLAN) for (const n of p.scenes) if (!seen.some((x) => covers(n, x))) report.noScene.push(`${p.label}: no ${n} scene in this world`);
  return report;
})();
"""
(CAT / "crooked-moon-intro-keys.apply.js").write_text(JS.replace("__PLAN__", json.dumps(plan, ensure_ascii=False)), encoding="utf-8")
print(len(plan), "intro keys planned;", sum(len(p["scenes"]) for p in plan), "scene placements")
