// Deck Command — the Crooked House's ACTION KEYS. TEST WORLD ONLY. Paste into the GM's console.
//
// One macro per beat, in the Macros folder "Deck Command - Crooked House", placed on the board of every scene
// it belongs to: PAGE 1 the room keys, PAGE 2 what the house does anywhere (the DM's layout, 2026-09-20).
// Creates or updates, never deletes; a key he has moved stays where he put it.
//
// It also PROVISIONS what the keys name and the shipped map lacks: a hidden light at the parlour hearth (the
// book puts none there at all) and a flag on the front door. Both are made once and reported.
(async () => {
  if (game.world?.id !== "offline-test") return { refused: `world is ${game.world?.id}, not offline-test` };
  if (!game.user?.isGM) return { refused: "not a GM" };
  const ID = "deck-command";
  const MOD = "mobile-command";
  const PLAN = [{"a": "A80", "label": "Porch bolt", "img": "icons/magic/lightning/bolt-strike-blue.webp", "page": 1, "scenes": ["12.1"], "note": "Lightning beside the porch, and its thunder a second or two later.", "command": "// Deck Command action key A80 — Lightning beside the porch, and its thunder a second or two later.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.fx({\"id\": \"lightning\"});\n})();"}, {"a": "A81", "label": "Front door", "img": "icons/svg/door-open-outline.svg", "page": 1, "scenes": ["12.1"], "note": "The front door swings open on its own.", "command": "// Deck Command action key A81 — The front door swings open on its own.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.door({\"cm\": \"door:front\", \"state\": \"open\"});\n})();"}, {"a": "A83", "label": "Hearth lit", "img": "icons/magic/fire/flame-burning-campfire-orange.webp", "page": 1, "scenes": ["12.1"], "note": "A pleasant fire catches in the parlour as the seance begins.", "command": "// Deck Command action key A83 — A pleasant fire catches in the parlour as the seance begins.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.light({\"cm\": \"light:hearth\", \"on\": true});\n  await act.loop({\"cm\": \"12.1:sound:3\", \"on\": true});\n})();"}, {"a": "A84", "label": "Hearth out", "img": "icons/magic/unholy/orb-smoking-green.webp", "page": 1, "scenes": ["12.1"], "note": "The fire dies, the loop stops, and darkness falls on the parlour.", "command": "// Deck Command action key A84 — The fire dies, the loop stops, and darkness falls on the parlour.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.light({\"cm\": \"light:hearth\", \"on\": false});\n  await act.loop({\"cm\": \"12.1:sound:3\", \"on\": false});\n})();"}, {"a": "A89", "label": "Waltz", "img": "icons/tools/instruments/harp-lap-brown.webp", "page": 1, "scenes": ["12.1"], "note": "The harpsichord's waltz, heard across the whole first floor.", "command": "// Deck Command action key A89 — The harpsichord's waltz, heard across the whole first floor.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.loop({\"cm\": \"12.1:sound:1\", \"on\": true});\n})();"}, {"a": "A90", "label": "Waltz off", "img": "icons/svg/sound-off.svg", "page": 1, "scenes": ["12.1"], "note": "The waltz stops on the Performance success.", "command": "// Deck Command action key A90 — The waltz stops on the Performance success.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.loop({\"cm\": \"12.1:sound:1\", \"on\": false});\n})();"}, {"a": "A93", "label": "Oven bursts", "img": "icons/magic/death/skull-energy-light-purple.webp", "page": 1, "scenes": ["12.1"], "note": "The oven door bursts open in flame and the screaming stops.", "command": "// Deck Command action key A93 — The oven door bursts open in flame and the screaming stops.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.cue({\"cm\": \"room:oven\", \"on\": false});\n  await act.roomSound({\"src\": \"assets/Personal/SFX/Magic Spells Vol 2/Fire/Fireball J.wav\", \"volume\": 0.8, \"at\": {\"x\": 2170, \"y\": 910}, \"radius\": 30});\n})();"}, {"a": "A94", "label": "Oven quiet", "img": "icons/svg/sound-off.svg", "page": 1, "scenes": ["12.1"], "note": "The screams behind the oven stop when the glyph is disarmed.", "command": "// Deck Command action key A94 — The screams behind the oven stop when the glyph is disarmed.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.cue({\"cm\": \"room:oven\", \"on\": false});\n})();"}, {"a": "A95", "label": "Petunia go", "img": "icons/magic/death/hand-undead-skeleton-fire-green.webp", "page": 1, "scenes": ["12.1"], "note": "Petunia fades in peace and her bench falls quiet.", "command": "// Deck Command action key A95 — Petunia fades in peace and her bench falls quiet.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.cue({\"cm\": \"room:petunia\", \"on\": false});\n  await act.tokens({\"match\": [\"Petunia\"], \"show\": false});\n})();"}, {"a": "A125", "label": "Door slams", "img": "icons/svg/door-open-outline.svg", "page": 2, "scenes": ["12.1", "12.2", "12.3", "12.4"], "note": "The nearest door opens or shuts by itself. A locked one is left alone.", "command": "// Deck Command action key A125 — The nearest door opens or shuts by itself. A locked one is left alone.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.door({\"state\": \"toggle\"});\n})();"}, {"a": "A126", "label": "Locks it", "img": "icons/svg/door-locked-outline.svg", "page": 2, "scenes": ["12.1", "12.2", "12.3", "12.4"], "note": "The nearest door locks behind them.", "command": "// Deck Command action key A126 — The nearest door locks behind them.\n// Generated by mobile-command/tools/gen-house-keys.py. Every verb lives in deck-command's action\n// runtime, so this macro is a script of calls and never a mechanism of its own.\nconst act = game.modules.get(\"deck-command\")?.api?.act;\nif (!act) return ui.notifications.warn(\"Deck Command is not active, so this key has nothing to call.\");\n(async () => {\n  await act.door({\"state\": \"locked\"});\n})();"}];
  const PROVISION = {"12.1": {"lights": [{"cm": "light:hearth", "x": 770, "y": 1750, "dim": 18, "bright": 8, "color": "#ff9a3c", "alpha": 0.45}], "doors": [{"cm": "door:front", "near": [1330, 2730]}]}};
  const report = { made: [], created: [], updated: [], placed: [], alreadyThere: [], missing: [] };

  const numOf = (name) => /^(\d{1,2}(?:\.\d{1,2})+)\s/.exec(name)?.[1] ?? null;
  const covers = (planNum, sceneNum) => sceneNum === planNum || sceneNum.startsWith(`${planNum}.`);

  // ── 1. make what the keys will name
  for (const scene of game.scenes.contents) {
    const num = numOf(scene.name);
    const want = num && PROVISION[num];
    if (!want) continue;
    for (const l of want.lights ?? []) {
      if (scene.lights.find((x) => x.getFlag(MOD, "cm") === l.cm)) continue;
      await scene.createEmbeddedDocuments("AmbientLight", [{
        x: l.x, y: l.y, hidden: true, flags: { [MOD]: { cm: l.cm } },
        config: { dim: l.dim, bright: l.bright, color: l.color, alpha: l.alpha, animation: { type: "torch", speed: 2, intensity: 3 } },
      }]);
      report.made.push(`${scene.name}: light ${l.cm}`);
    }
    for (const d of want.doors ?? []) {
      if (scene.walls.find((w) => w.getFlag(MOD, "cm") === d.cm)) continue;
      const doors = scene.walls.filter((w) => w.door > 0);
      if (!doors.length) { report.missing.push(`${scene.name}: no doors to flag as ${d.cm}`); continue; }
      const mid = (w) => ({ x: (w.c[0] + w.c[2]) / 2, y: (w.c[1] + w.c[3]) / 2 });
      const best = doors.reduce((b, w) => {
        const m = mid(w);
        const dist = (m.x - d.near[0]) ** 2 + (m.y - d.near[1]) ** 2;
        return !b || dist < b.dist ? { w, dist } : b;
      }, null);
      await best.w.setFlag(MOD, "cm", d.cm);
      report.made.push(`${scene.name}: ${d.cm} -> the door at ${Math.round(mid(best.w).x)},${Math.round(mid(best.w).y)}`);
    }
  }

  // ── 2. the macros
  const folderName = "Deck Command - Crooked House";
  const folder = game.folders.find((f) => f.type === "Macro" && f.name === folderName)
    ?? await Folder.implementation.create({ name: folderName, type: "Macro" });
  const macros = {};
  for (const p of PLAN) {
    const data = { name: p.label, type: "script", img: p.img, command: p.command, folder: folder.id, flags: { [ID]: { house: p.a } } };
    let m = game.macros.find((x) => x.flags?.[ID]?.house === p.a);
    if (m) { await m.update(data); report.updated.push(`${p.a} ${p.label}`); }
    else { m = await Macro.implementation.create(data); report.created.push(`${p.a} ${p.label}`); }
    macros[p.a] = m;
  }

  // ── 3. onto the boards, on the page the DM asked for
  const SLOTS = 10;
  for (const scene of game.scenes.contents) {
    const num = numOf(scene.name);
    if (!num) continue;
    const wanted = PLAN.filter((p) => p.scenes.some((n) => covers(n, num)));
    if (!wanted.length) continue;
    const raw = scene.flags?.[ID]?.sounds;
    const list = Array.isArray(raw) ? raw : raw && typeof raw === "object" ? Object.values(raw) : [];
    const pages = list.map((pg) => Array.from({ length: SLOTS }, (_, i) => {
      const v = (Array.isArray(pg) ? pg : Object.values(pg ?? {}))[i];
      return typeof v === "string" && v ? v : null;
    }));
    let changed = false;
    for (const p of wanted) {
      const uuid = macros[p.a].uuid;
      if (pages.some((pg) => pg.includes(uuid))) { report.alreadyThere.push(`${scene.name}: ${p.label}`); continue; }
      while (pages.length < p.page) pages.push(Array(SLOTS).fill(null));
      let pg = p.page - 1;
      let i = pages[pg].indexOf(null);
      while (i < 0) { // that page is full — the next one along, never somebody else's key pushed out
        pg++;
        if (!pages[pg]) pages.push(Array(SLOTS).fill(null));
        i = pages[pg].indexOf(null);
      }
      pages[pg][i] = uuid;
      changed = true;
      report.placed.push(`${scene.name}: ${p.label} -> page ${pg + 1}, box ${i + 1}`);
    }
    if (changed) await scene.setFlag(ID, "sounds", pages);
  }

  console.log("Crooked House action keys", report);
  ui.notifications.info(`Action keys: ${report.created.length} created, ${report.updated.length} updated, `
    + `${report.placed.length} placed, ${report.made.length} things provisioned`
    + (report.missing.length ? ` - could not: ${report.missing.join("; ")}` : "."));
  return report;
})();
